% Generated by ADiMat 0.6.6-5530 (00419e1f)
% © 2001-2008 Andre Vehreschild <vehreschild@sc.rwth-aachen.de>
% © 2009-2018 Johannes Willkomm <johannes@johannes-willkomm.de>
% TU Darmstadt, 64289 Darmstadt, Germany
% Visit us on the web at http://www.adimat.de/
% Report bugs to johannes@johannes-willkomm.de
%
%                             DISCLAIMER
% 
% ADiMat was prepared as part of an employment at the Institute for Scientific Computing,
% RWTH Aachen University, Germany and at the Institute for Scientific Computing,
% TU Darmstadt, Germany and is provided AS IS. 
% NEITHER THE AUTHOR(S), THE GOVERNMENT OF THE FEDERAL REPUBLIC OF GERMANY
% NOR ANY AGENCY THEREOF, NOR THE RWTH AACHEN UNIVERSITY, NOT THE TU DARMSTADT,
% INCLUDING ANY OF THEIR EMPLOYEES OR OFFICERS, MAKES ANY WARRANTY, EXPRESS OR IMPLIED,
% OR ASSUMES ANY LEGAL LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS,
% OR USEFULNESS OF ANY INFORMATION OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE
% WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.
%
% Parameters:
%  - dependents=out
%  - independents=U
%  - inputEncoding=ISO-8859-1
%
% Functions in this file: d_para
%

function [d_out out] = d_para(d_U, U)
   d_tmpca3 = adimat_opdiff_sum(adimat_opdiff_subsref(d_U, struct('type', '()', 'subs', {{2}})), d_zeros(3));
   tmpca3 = U(2) + 3;
   d_tmpca2 = adimat_opdiff_pow_right(d_tmpca3, tmpca3, 4);
   tmpca2 = tmpca3 ^ 4;
   d_tmpca1 = adimat_opdiff_pow_right(adimat_opdiff_subsref(d_U, struct('type', '()', 'subs', {{1}})), U(1), 2);
   tmpca1 = U(1) ^ 2;
   d_out = adimat_opdiff_sum(d_tmpca1, d_tmpca2, d_zeros(6));
   out = tmpca1 + tmpca2 + 6;
end
